# APP
APP_USER=admin
APP_PASSWORD=password

# DB
DB_DATABASE=silver-micro
DB_PASSWORD=${APP_PASSWORD}
DB_USER=${DB_DATABASE}
DB_VENDOR=POSTGRES
DB_ADDR=db
DB_SCHEMA=public
DB_PORT=5432
DB_URL=postgres://${DB_USER}:${DB_PASSWORD}@${DB_ADDR}:5432/${DB_DATABASE}

# POSTGRES
POSTGRES_PASSWORD=${DB_PASSWORD}
POSTGRES_DB=${DB_DATABASE}
POSTGRES_USER=${DB_USER}

# DOCKER
PROJECT=silver-micro